# Basic zsh configuration
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
setopt histignorealldups
setopt autocd
setopt extendedglob
setopt interactive_comments
setopt prompt_subst
setopt extended_history
setopt share_history
setopt hist_expire_dups_first
setopt hist_find_no_dups
setopt hist_ignore_space
setopt hist_verify
unsetopt beep

# Basic completion system
autoload -Uz compinit
compinit

# Fish-like autosuggestions and syntax highlighting
# Note: You need to install these plugins:
# zsh-syntax-highlighting: https://github.com/zsh-users/zsh-syntax-highlighting
# zsh-autosuggestions: https://github.com/zsh-users/zsh-autosuggestions

# Check if plugins exist and source them
[ -f ~/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] && \
  source ~/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

[ -f ~/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ] && \
  source ~/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# Configure autosuggestions
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=8"
bindkey '^[[Z' autosuggest-accept  # Shift+Tab to accept suggestion

# Vim mode
bindkey -v
export KEYTIMEOUT=1

# Vim mode cursor change
function zle-keymap-select {
  if [[ ${KEYMAP} == vicmd ]] || [[ $1 = 'block' ]]; then
    echo -ne '\e[1 q'  # Block cursor
  elif [[ ${KEYMAP} == main ]] || [[ ${KEYMAP} == viins ]] || [[ ${KEYMAP} = '' ]] || [[ $1 = 'beam' ]]; then
    echo -ne '\e[5 q'  # Beam cursor
  fi
}
zle -N zle-keymap-select

# Initialize cursor as beam
echo -ne '\e[5 q'
preexec() { echo -ne '\e[5 q' ;}

# Better vim mode experience
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey -M vicmd '^[[A' up-line-or-beginning-search
bindkey -M vicmd '^[[B' down-line-or-beginning-search
bindkey -M viins '^[[A' up-line-or-beginning-search
bindkey -M viins '^[[B' down-line-or-beginning-search

# Edit command line in Vim with v in normal mode
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey -M vicmd 'v' edit-command-line

# More Vim-like bindings
bindkey -M vicmd 'y' vi-yank
bindkey -M vicmd 'Y' vi-yank-eol
bindkey -M vicmd 'u' undo
bindkey -M vicmd '^R' redo
bindkey -M vicmd 'gg' beginning-of-buffer-or-history
bindkey -M vicmd 'G' end-of-buffer-or-history

# Better history search in vim mode
bindkey -M vicmd '/' history-incremental-pattern-search-backward
bindkey -M vicmd '?' history-incremental-pattern-search-forward

# Visual mode like in Vim
bindkey -M vicmd 'V' visual-mode

# Additional key bindings
bindkey '^[[H' beginning-of-line    # Home key
bindkey '^[[F' end-of-line          # End key
bindkey '^[[3~' delete-char         # Delete key
bindkey '^H' backward-delete-char   # Backspace
bindkey '^?' backward-delete-char   # Backspace alternative

# Simple theme with git information
autoload -Uz vcs_info
precmd() { vcs_info }

zstyle ':vcs_info:git:*' formats '%F{yellow}(%b)%f '
zstyle ':vcs_info:*' enable git

# Prompt setup
PROMPT='%F{green}%n@%m%f %F{blue}%~%f ${vcs_info_msg_0_}%F{%(?.green.red)}%(!.#.$)%f '
RPROMPT='%F{cyan}[%*]%f'  # Show time on the right

# Aliases based on your common commands
alias l='ls -la'
alias g='git'
alias rg='rg -M200'
alias fd='fd -i'
alias pc='podman-compose'
alias pcu='podman-compose up -d'
alias pcd='podman-compose down'
alias pcl='podman-compose logs -f'
alias pcr='podman-compose restart'

# Git aliases
alias gco='git checkout'
alias gcob='git checkout $(git for-each-ref --sort=-committerdate refs/heads/ --format="%(refname:short)" | head -n 10 | fzf)'
alias gst='git status'
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gl='git log'
alias gp='git push'
alias ggpush='git push origin $(git branch --show-current)'

# Docker/Podman shortcuts
alias dps='docker ps'
alias dls='docker image ls'
alias pps='podman ps'
alias pls='podman image ls'
alias prm='podman rm'
alias prun='podman run --rm -ti'
alias dc='docker-compose'
alias dcu='docker-compose up -d'
alias dcd='docker-compose down'
alias dcl='docker-compose logs -f'

# Development shortcuts
alias y='yarn'
alias yi='yarn install'
alias yd='yarn dev'
alias yb='yarn build'
alias yt='yarn test'
alias v='nvim'
alias d='deno'
alias dr='deno run'
alias dt='deno task'
alias aider='aider --no-gitignore'

# Environment variables
export EDITOR='nvim'
export LANG=en_US.UTF-8
export LC_ALL=$LANG
export LC_CTYPE=$LANG
export RIPGREP_CONFIG_PATH=~/.config/ripgrep

# FZF integration (if installed)
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Node version manager (if you use fnm)
FNM_PATH="/home/fernando/.fnm"
if [ -d "$FNM_PATH" ]; then
  export PATH="/home/fernando/.fnm:$PATH"
  eval "`fnm env`"
fi

# Path additions
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH:$HOME/.cargo/bin:$HOME/.tfenv/bin:$HOME/dotfiles/bin/"

# Fish-like directory navigation
# Use Alt+Up to go up a directory
cdUndoKey() {
  pushd .. > /dev/null
  zle reset-prompt
}
zle -N cdUndoKey
bindkey '^[[1;3A' cdUndoKey

# Quick directory navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# Load any local customizations
[ -f ~/.zshrc.local ] && source ~/.zshrc.local

# Keep useful aliases from previous config
alias finalet='tmuxp load ~/finale.tmuxp.yaml'
alias ndebug=NODE_OPTIONS='--inspect-brk'


# SSH agent setup
if [[ -f "$HOME/dotfiles/bin/persistent-ssh-agent" ]]; then
    # Source the script to ensure environment variables are set in current shell
    source "$HOME/dotfiles/bin/persistent-ssh-agent"
fi

if [[ -f "$HOME/dotfiles/zsh/env" ]]; then
    source "$HOME/dotfiles/zsh/env"
fi
